---
title: Dealing with failures by writing a CV?
author: ''
date: '2022-04-08'
slug: []
categories: []
tags: []
draft: true
---

I am the sum of all my experiences; successes *and* failures. For each project that eventually succeeds, there are some that never pan out and a few more that I give up on.

This concept can be traced back to [this 2010 article](https://www.nature.com/articles/nj7322-467a) in Nature by [Melanie I. Stefan, PhD](http://melaniestefan.net/index.html). In her piece, she recounts an experience that resonates with me:

> "As scientists, we construct a narrative of success that renders our setbacks invisible both to ourselves and to others. Often, other scientists' careers seem to be a constant, streamlined series of triumphs. Therefore, whenever we experience an individual failure, we feel alone and dejected."

The purpose of a CV of failures is to change this narrative. It helps oneself and others to deal with setbacks by painting a more transparent, fully fledged, and ultimately more humane image of its author. Dr Stefan's idea has been adapted by many others - for instance [here](https://haushofer.ne.su.se/Johannes_Haushofer_CV_of_Failures.pdf), [here](https://738d9b89-a-62cb3a1a-s-sites.googlegroups.com/site/bradleyvoytek/professional/voytek_cv.pdf?attachauth=ANoY7crskBVzhljJEo8y7JcPQ8PQxey1EcbvFZhwGPcItVZKfltkoGnfSMubTzVVCRNIZ6XfPYuiu-I_qZmf9W1hZiDEdQVDh9PXUYZJQzTFjCdOFgZAcUqiRAry8OR9f5HRVj95a-dIB2p2vpWXgHqsVtTSo9ZrbFZriLO--UVR4vzvlpvb2Ueq1VEdlwPQ3lsOqQ1W8HsMWcwTC7S1_qVdvmdkkw_LFALCgBLjkNnDvU-E9JzBQWE%3D&attredirects=0), [here](http://everydayscientist.com/CV/sjl_CV-failures.pdf), and [here](https://www.dr-marc-reid.com/cv-of-failures).

In writing my own [CV of failures](weidinger_failures.pdf) and sharing it alongside my "normal" resume, I hope to give you a better idea of where I come from, who I have become, what it took to become who I am now, and of the potential that my future holds. The idea of a flawless career is illusive but for the hurdles we take along the way and our persistence to overcome them.
